# Generated by Django 5.2.7 on 2025-10-03 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationship",
            name="operation",
        ),
        migrations.RemoveField(
            model_name="operationship",
            name="ship",
        ),
        migrations.AlterModelOptions(
            name="ship",
            options={"verbose_name": "Vaisseau", "verbose_name_plural": "Vaisseaux"},
        ),
        migrations.AlterModelOptions(
            name="shiproletemplate",
            options={
                "verbose_name": "Rôle (modèle)",
                "verbose_name_plural": "Rôles (modèles)",
            },
        ),
        migrations.AlterField(
            model_name="ship",
            name="max_crew",
            field=models.PositiveSmallIntegerField(verbose_name="Équipage maximum"),
        ),
        migrations.AlterField(
            model_name="ship",
            name="min_crew",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Équipage minimum"
            ),
        ),
        migrations.AlterField(
            model_name="ship",
            name="name",
            field=models.CharField(
                max_length=80, unique=True, verbose_name="Nom du vaisseau"
            ),
        ),
        migrations.AlterField(
            model_name="shiproletemplate",
            name="role_name",
            field=models.CharField(max_length=40, verbose_name="Rôle"),
        ),
        migrations.AlterField(
            model_name="shiproletemplate",
            name="ship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_templates",
                to="ops.ship",
                verbose_name="Vaisseau",
            ),
        ),
        migrations.AlterField(
            model_name="shiproletemplate",
            name="slots",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Nombre de places"
            ),
        ),
        migrations.CreateModel(
            name="RoleSlot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=40, verbose_name="Rôle")),
                (
                    "index",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="N° de place"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Libre"),
                            ("assigned", "Assigné"),
                            ("confirmed", "Confirmé"),
                        ],
                        default="open",
                        max_length=16,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_slots",
                        to="ops.ship",
                        verbose_name="Vaisseau",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Place de rôle",
                "verbose_name_plural": "Places de rôle",
                "unique_together": {("ship", "role_name", "index")},
            },
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
        migrations.DeleteModel(
            name="Operation",
        ),
        migrations.DeleteModel(
            name="OperationShip",
        ),
    ]
