# Generated by Django 5.2.7 on 2025-10-03 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0002_remove_operationship_operation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="category",
            field=models.CharField(
                choices=[
                    ("LF", "Chasseur léger"),
                    ("MF", "Chasseur moyen"),
                    ("HF", "Chasseur lourd"),
                    ("MR", "Multirôle"),
                    ("CAP", "Capital"),
                ],
                default="MR",
                max_length=3,
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="roleslot",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
    ]
