# Generated by Django 5.2.7 on 2025-10-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0004_alter_roleslot_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="cargo_capacity",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Soute (SCU)"
            ),
        ),
        migrations.AddField(
            model_name="ship",
            name="manufacturer",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Constructeur"
            ),
        ),
        migrations.AddField(
            model_name="ship",
            name="role",
            field=models.CharField(blank=True, max_length=120, verbose_name="Type"),
        ),
        migrations.AlterField(
            model_name="ship",
            name="name",
            field=models.CharField(
                max_length=120, unique=True, verbose_name="Nom du vaisseau"
            ),
        ),
    ]