# Generated by Django 5.2.7 on 2025-10-04 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0006_load_ship_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="Nom de l'opération"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Opération actuelle"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mise à jour"),
                ),
                (
                    "highlighted_ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="highlighted_in_operations",
                        to="ops.ship",
                        verbose_name="Vaisseau mis en avant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opération",
                "verbose_name_plural": "Opérations",
            },
        ),
    ]