# Generated by Django 5.2.7 on 2025-10-04 17:15

import django.db.models.deletion
from django.db import migrations, models


def copy_highlighted_ships_forward(apps, schema_editor):
    Operation = apps.get_model("ops", "Operation")
    OperationHighlightedShip = apps.get_model("ops", "OperationHighlightedShip")

    assignments = []
    for operation in Operation.objects.exclude(highlighted_ship__isnull=True):
        assignments.append(
            OperationHighlightedShip(
                operation_id=operation.pk,
                ship_id=operation.highlighted_ship_id,
            )
        )

    if assignments:
        OperationHighlightedShip.objects.bulk_create(assignments)


def copy_highlighted_ships_backward(apps, schema_editor):
    Operation = apps.get_model("ops", "Operation")
    OperationHighlightedShip = apps.get_model("ops", "OperationHighlightedShip")

    for link in OperationHighlightedShip.objects.all():
        Operation.objects.filter(pk=link.operation_id).update(
            highlighted_ship_id=link.ship_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0008_update_group_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationHighlightedShip",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pilot_name",
                    models.CharField(blank=True, max_length=120, verbose_name="Pilote"),
                ),
                (
                    "gunner_name",
                    models.CharField(blank=True, max_length=120, verbose_name="Gunner"),
                ),
                (
                    "infantry_name",
                    models.CharField(blank=True, max_length=120, verbose_name="À pied"),
                ),
                (
                    "torpedo_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Torpille"
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlighted_ship_links",
                        to="ops.operation",
                        verbose_name="Opération",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlighted_operation_links",
                        to="ops.ship",
                        verbose_name="Vaisseau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaisseau mis en avant",
                "verbose_name_plural": "Vaisseaux mis en avant",
                "unique_together": {("operation", "ship")},
            },
        ),
        migrations.AddField(
            model_name="operation",
            name="highlighted_ships",
            field=models.ManyToManyField(
                blank=True,
                related_name="highlighted_in_operations",
                through="ops.OperationHighlightedShip",
                to="ops.ship",
                verbose_name="Vaisseaux mis en avant",
            ),
        ),
        migrations.RunPython(
            copy_highlighted_ships_forward,
            reverse_code=copy_highlighted_ships_backward,
        ),
        migrations.RemoveField(
            model_name="operation",
            name="highlighted_ship",
        ),
    ]