# Generated by Django 5.2.7 on 2025-10-04 17:32

import django.db.models.deletion
from django.db import migrations, models


ROLE_FIELD_MAP = {
    "pilot": "pilot_name",
    "gunner": "gunner_name",
    "infantry": "infantry_name",
    "torpedo": "torpedo_name",
}


def copy_roles_forward(apps, schema_editor):
    Assignment = apps.get_model("ops", "OperationHighlightedCrewAssignment")
    HighlightedShip = apps.get_model("ops", "OperationHighlightedShip")

    assignments = []
    for link in HighlightedShip.objects.all():
        for role, field_name in ROLE_FIELD_MAP.items():
            name = getattr(link, field_name, "") or ""
            name = name.strip()
            if not name:
                continue
            assignments.append(
                Assignment(
                    highlighted_ship_id=link.pk,
                    role=role,
                    crew_name=name,
                    order=1,
                )
            )

    if assignments:
        Assignment.objects.bulk_create(assignments)


def copy_roles_backward(apps, schema_editor):
    Assignment = apps.get_model("ops", "OperationHighlightedCrewAssignment")
    HighlightedShip = apps.get_model("ops", "OperationHighlightedShip")

    assignments = Assignment.objects.select_related("highlighted_ship")
    grouped = {}
    for assignment in assignments:
        grouped.setdefault(assignment.highlighted_ship_id, {}).setdefault(
            assignment.role, []
        ).append(assignment.crew_name)

    for ship_id, role_data in grouped.items():
        update_kwargs = {}
        for role, field_name in ROLE_FIELD_MAP.items():
            names = role_data.get(role)
            update_kwargs[field_name] = names[0] if names else ""
        HighlightedShip.objects.filter(pk=ship_id).update(**update_kwargs)


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0009_remove_operation_highlighted_ship_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationHighlightedCrewAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("pilot", "Pilote"),
                            ("gunner", "Gunner"),
                            ("infantry", "À pied"),
                            ("torpedo", "Torpille"),
                        ],
                        max_length=16,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "crew_name",
                    models.CharField(max_length=120, verbose_name="Membre d’équipage"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Ordre"),
                ),
                (
                    "highlighted_ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew_assignments",
                        to="ops.operationhighlightedship",
                        verbose_name="Vaisseau mis en avant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignation de rôle",
                "verbose_name_plural": "Assignations de rôle",
                "ordering": ("highlighted_ship", "role", "order", "id"),
            },
        ),
        migrations.RunPython(copy_roles_forward, reverse_code=copy_roles_backward),
        migrations.RemoveField(
            model_name="operationhighlightedship",
            name="gunner_name",
        ),
        migrations.RemoveField(
            model_name="operationhighlightedship",
            name="infantry_name",
        ),
        migrations.RemoveField(
            model_name="operationhighlightedship",
            name="pilot_name",
        ),
        migrations.RemoveField(
            model_name="operationhighlightedship",
            name="torpedo_name",
        ),
    ]