"""Automatically generated ship catalog data."""

SHIPS_DATA = [
    {'name': 'Avenger Stalker', 'manufacturer': 'Aegis', 'role': 'Interdiction', 'crew': '1', 'cargo': '-'},
    {'name': 'Avenger Titan', 'manufacturer': 'Aegis', 'role': 'Light Freight', 'crew': '1', 'cargo': '8'},
    {'name': 'Avenger Titan Renegade', 'manufacturer': 'Aegis', 'role': 'Light Freight', 'crew': '1', 'cargo': '8'},
    {'name': 'Avenger Warlock', 'manufacturer': 'Aegis', 'role': 'Interdiction', 'crew': '1', 'cargo': '-'},
    {'name': 'Cutter (drone) (In Concept)', 'manufacturer': 'Aegis', 'role': 'Snub Salvage', 'crew': '?', 'cargo': '-'},
    {'name': 'Eclipse', 'manufacturer': 'Aegis', 'role': 'Stealth Bomber', 'crew': '1', 'cargo': '-'},
    {'name': 'Gladius', 'manufacturer': 'Aegis', 'role': 'Light Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Gladius Pirate', 'manufacturer': 'Aegis', 'role': 'Light Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Gladius Valiant', 'manufacturer': 'Aegis', 'role': 'Light Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Hammerhead', 'manufacturer': 'Aegis', 'role': 'Heavy Gunship', 'crew': '3 - 9', 'cargo': '40'},
    {'name': 'Hammerhead Best In Show', 'manufacturer': 'Aegis', 'role': 'Heavy Gunship', 'crew': '3 - 9', 'cargo': '40'},
    {'name': 'Idris-M', 'manufacturer': 'Aegis', 'role': 'Frigate', 'crew': '8 - 28', 'cargo': '1326'},
    {'name': 'Idris-P', 'manufacturer': 'Aegis', 'role': 'Frigate', 'crew': '8 - 28', 'cargo': '1374'},
    {'name': 'Javelin (In Production)', 'manufacturer': 'Aegis', 'role': 'Destroyer', 'crew': '12 - 80', 'cargo': '3446'},
    {'name': 'Nautilus (In Concept)', 'manufacturer': 'Aegis', 'role': 'Minelayer', 'crew': '4 - 8', 'cargo': '64'},
    {'name': 'Nautilus Solstice (In Concept)', 'manufacturer': 'Aegis', 'role': 'Minelayer', 'crew': '4 - 8', 'cargo': '64'},
    {'name': 'Reclaimer', 'manufacturer': 'Aegis', 'role': 'Heavy Salvage', 'crew': '4 - 5', 'cargo': '420'},
    {'name': 'Reclaimer Best In Show', 'manufacturer': 'Aegis', 'role': 'Heavy Salvage', 'crew': '4 - 5', 'cargo': '420'},
    {'name': 'Redeemer', 'manufacturer': 'Aegis', 'role': 'Gunship', 'crew': '3 - 5', 'cargo': '2'},
    {'name': 'Retaliator', 'manufacturer': 'Aegis', 'role': 'Heavy Gunship, Modular', 'crew': '4 - 7', 'cargo': '-'},
    {'name': 'Retaliator Bomber', 'manufacturer': 'Aegis', 'role': 'Heavy Gunship, Bomber, Modular', 'crew': '4 - 7', 'cargo': '-'},
    {'name': 'Sabre', 'manufacturer': 'Aegis', 'role': 'Stealth', 'crew': '1', 'cargo': '-'},
    {'name': 'Sabre Comet', 'manufacturer': 'Aegis', 'role': 'Stealth', 'crew': '1', 'cargo': '-'},
    {'name': 'Sabre Firebird', 'manufacturer': 'Aegis', 'role': 'Medium Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Sabre Peregrine', 'manufacturer': 'Aegis', 'role': 'Racing', 'crew': '1', 'cargo': '-'},
    {'name': 'Sabre Raven', 'manufacturer': 'Aegis', 'role': 'Stealth, Interdiction', 'crew': '1', 'cargo': '-'},
    {'name': 'Vanguard Harbinger', 'manufacturer': 'Aegis', 'role': 'Bomber', 'crew': '2', 'cargo': '-'},
    {'name': 'Vanguard Hoplite', 'manufacturer': 'Aegis', 'role': 'Dropship', 'crew': '2', 'cargo': '-'},
    {'name': 'Vanguard Sentinel', 'manufacturer': 'Aegis', 'role': 'Interdiction', 'crew': '2', 'cargo': '-'},
    {'name': 'Vanguard Warden', 'manufacturer': 'Aegis', 'role': 'Heavy Fighter', 'crew': '2', 'cargo': '-'},
    {'name': 'Vulcan (In Concept)', 'manufacturer': 'Aegis', 'role': 'Repair, Refuel', 'crew': '1 - 3', 'cargo': '12'},
    {'name': 'Arrow', 'manufacturer': 'Anvil', 'role': 'Light Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Asgard', 'manufacturer': 'Anvil', 'role': 'Dropship', 'crew': '1 - 2', 'cargo': '180'},
    {'name': 'Carrack', 'manufacturer': 'Anvil', 'role': 'Expedition', 'crew': '4 - 6', 'cargo': '456'},
    {'name': 'Carrack Expedition', 'manufacturer': 'Anvil', 'role': 'Expedition', 'crew': '4 - 6', 'cargo': '456'},
    {'name': 'Carrack Expedition w/C8X', 'manufacturer': 'Anvil', 'role': 'Expedition', 'crew': '4 - 6', 'cargo': '456'},
    {'name': 'Carrack w/C8X', 'manufacturer': 'Anvil', 'role': 'Expedition', 'crew': '4 - 6', 'cargo': '456'},
    {'name': 'Crucible (In Concept)', 'manufacturer': 'Anvil', 'role': 'Heavy Repair', 'crew': '3 - 8', 'cargo': '230'},
    {'name': 'F7A Hornet Mk2', 'manufacturer': 'Anvil', 'role': 'Medium Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'F7C Hornet Mk1', 'manufacturer': 'Anvil', 'role': 'Medium Fighter', 'crew': '1', 'cargo': '2'},
    {'name': 'F7C Hornet Mk2', 'manufacturer': 'Anvil', 'role': 'Medium Fighter', 'crew': '1', 'cargo': '2'},
    {'name': 'F7C Hornet Wildfire Mk1', 'manufacturer': 'Anvil', 'role': 'Medium Fighter', 'crew': '1', 'cargo': '2'},
    {'name': 'F7C-M Super Hornet Heartseeker Mk1', 'manufacturer': 'Anvil', 'role': 'Medium Fighter', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'F7C-M Super Hornet Mk1', 'manufacturer': 'Anvil', 'role': 'Medium Fighter', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'F7C-M Super Hornet Mk2', 'manufacturer': 'Anvil', 'role': 'Medium Fighter', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'F7C-R Hornet Tracker Mk1', 'manufacturer': 'Anvil', 'role': 'Pathfinder', 'crew': '1', 'cargo': '-'},
    {'name': 'F7C-R Hornet Tracker Mk2', 'manufacturer': 'Anvil', 'role': 'Pathfinder', 'crew': '1', 'cargo': '-'},
    {'name': 'F7C-S Hornet Ghost Mk1', 'manufacturer': 'Anvil', 'role': 'Stealth', 'crew': '1', 'cargo': '-'},
    {'name': 'F7C-S Hornet Ghost Mk2', 'manufacturer': 'Anvil', 'role': 'Stealth', 'crew': '1', 'cargo': '-'},
    {'name': 'F8C Lightning', 'manufacturer': 'Anvil', 'role': 'Heavy Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'F8C Lightning Executive', 'manufacturer': 'Anvil', 'role': 'Heavy Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Gladiator', 'manufacturer': 'Anvil', 'role': 'Bomber', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'Hawk', 'manufacturer': 'Anvil', 'role': 'Light Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Hurricane', 'manufacturer': 'Anvil', 'role': 'Heavy Fighter', 'crew': '2', 'cargo': '-'},
    {'name': 'Legionnaire (In Concept)', 'manufacturer': 'Anvil', 'role': 'Boarding', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'Liberator (In Concept)', 'manufacturer': 'Anvil', 'role': 'Carrier', 'crew': '1 - 2', 'cargo': '400'},
    {'name': 'Paladin (In Production)', 'manufacturer': 'Anvil', 'role': 'Gunship', 'crew': '1', 'cargo': '-'},
    {'name': 'Pisces C8', 'manufacturer': 'Anvil', 'role': 'Pathfinder', 'crew': '1 - 3', 'cargo': '4'},
    {'name': 'Pisces C8R Rescue', 'manufacturer': 'Anvil', 'role': 'Medical', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'Pisces C8X Expedition', 'manufacturer': 'Anvil', 'role': 'Pathfinder', 'crew': '1 - 3', 'cargo': '4'},
    {'name': 'Terrapin', 'manufacturer': 'Anvil', 'role': 'Pathfinder', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'Terrapin Medic', 'manufacturer': 'Anvil', 'role': 'Medical', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'Valkyrie', 'manufacturer': 'Anvil', 'role': 'Dropship', 'crew': '1 - 5', 'cargo': '90'},
    {'name': 'Valkyrie Liberator', 'manufacturer': 'Anvil', 'role': 'Dropship', 'crew': '1 - 5', 'cargo': '90'},
    {'name': 'Khartu-Al', 'manufacturer': 'AopoA', 'role': 'Light Fighter', 'crew': '1', 'cargo': '-'},
    {'name': "San'tok.yai", 'manufacturer': 'AopoA', 'role': 'Light Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'MOLE', 'manufacturer': 'ARGO', 'role': 'Mining, Prospecting', 'crew': '2 - 4', 'cargo': '96'},
    {'name': 'MOLE Carbon', 'manufacturer': 'ARGO', 'role': 'Mining, Prospecting', 'crew': '2 - 4', 'cargo': '96'},
    {'name': 'MOLE Talus', 'manufacturer': 'ARGO', 'role': 'Mining, Prospecting', 'crew': '2 - 4', 'cargo': '96'},
    {'name': 'MPUV-1C Cargo', 'manufacturer': 'ARGO', 'role': 'Light Freight', 'crew': '1', 'cargo': '2'},
    {'name': 'MPUV-1P Personnel', 'manufacturer': 'ARGO', 'role': 'Passenger', 'crew': '1', 'cargo': '2'},
    {'name': 'MPUV-1T Tractor', 'manufacturer': 'ARGO', 'role': 'Freight', 'crew': '1', 'cargo': '-'},
    {'name': 'RAFT', 'manufacturer': 'ARGO', 'role': 'Medium Freight', 'crew': '1 - 2', 'cargo': '192'},
    {'name': 'SRV', 'manufacturer': 'ARGO', 'role': 'Search and Rescue', 'crew': '1', 'cargo': '12'},
    {'name': 'Defender', 'manufacturer': 'Banu', 'role': 'Light Fighter', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'Merchantman (In Concept)', 'manufacturer': 'Banu', 'role': 'Heavy Freight', 'crew': '4 - 8', 'cargo': '2880'},
    {'name': 'Mustang Alpha', 'manufacturer': 'CNOU', 'role': 'Light Freight', 'crew': '1', 'cargo': '4'},
    {'name': 'Mustang Alpha Vindicator', 'manufacturer': 'CNOU', 'role': 'Light Freight', 'crew': '1', 'cargo': '4'},
    {'name': 'Mustang Beta', 'manufacturer': 'CNOU', 'role': 'Pathfinder', 'crew': '1', 'cargo': '-'},
    {'name': 'Mustang Delta', 'manufacturer': 'CNOU', 'role': 'Light Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Mustang Gamma', 'manufacturer': 'CNOU', 'role': 'Racing', 'crew': '1', 'cargo': '-'},
    {'name': 'Mustang Omega', 'manufacturer': 'CNOU', 'role': 'Racing', 'crew': '1', 'cargo': '-'},
    {'name': 'Nomad', 'manufacturer': 'CNOU', 'role': 'Freight', 'crew': '1', 'cargo': '24'},
    {'name': 'Pioneer (In Production)', 'manufacturer': 'CNOU', 'role': 'Heavy Construction', 'crew': '4 - 8', 'cargo': '1000'},
    {'name': 'Ares Inferno', 'manufacturer': 'Crusader', 'role': 'Heavy Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Ares Ion', 'manufacturer': 'Crusader', 'role': 'Heavy Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Genesis Starliner (In Concept)', 'manufacturer': 'Crusader', 'role': 'Large Passenger', 'crew': '2 - 8', 'cargo': '300'},
    {'name': 'Hercules A2', 'manufacturer': 'Crusader', 'role': 'Transport, Gunship, Bomber', 'crew': '1 - 8', 'cargo': '216'},
    {'name': 'Hercules C2', 'manufacturer': 'Crusader', 'role': 'Transport', 'crew': '1 - 2', 'cargo': '696'},
    {'name': 'Hercules M2', 'manufacturer': 'Crusader', 'role': 'Transport, Military', 'crew': '1 - 3', 'cargo': '522'},
    {'name': 'Intrepid', 'manufacturer': 'Crusader', 'role': 'Light Freight', 'crew': '1', 'cargo': '8'},
    {'name': 'Mercury Star Runner', 'manufacturer': 'Crusader', 'role': 'Medium Freight, Data', 'crew': '2 - 3', 'cargo': '114'},
    {'name': 'Spirit A1', 'manufacturer': 'Crusader', 'role': 'Bomber', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'Spirit C1', 'manufacturer': 'Crusader', 'role': 'Cargo', 'crew': '1 - 2', 'cargo': '64'},
    {'name': 'Spirit E1 (In Production)', 'manufacturer': 'Crusader', 'role': 'Passenger', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'Buccaneer', 'manufacturer': 'Drake', 'role': 'Interdiction', 'crew': '1', 'cargo': '-'},
    {'name': 'Caterpillar', 'manufacturer': 'Drake', 'role': 'Medium Freight', 'crew': '2 - 4', 'cargo': '576'},
    {'name': 'Caterpillar Best In Show', 'manufacturer': 'Drake', 'role': 'Medium Freight', 'crew': '2 - 4', 'cargo': '576'},
    {'name': 'Caterpillar Pirate', 'manufacturer': 'Drake', 'role': 'Medium Freight', 'crew': '2 - 4', 'cargo': '576'},
    {'name': 'Corsair', 'manufacturer': 'Drake', 'role': 'Exploration', 'crew': '2 - 4', 'cargo': '72'},
    {'name': 'Cutlass Black', 'manufacturer': 'Drake', 'role': 'Medium Freight, Fighter', 'crew': '1 - 2', 'cargo': '46'},
    {'name': 'Cutlass Black Best In Show', 'manufacturer': 'Drake', 'role': 'Medium Freight, Fighter', 'crew': '1 - 2', 'cargo': '46'},
    {'name': 'Cutlass Blue', 'manufacturer': 'Drake', 'role': 'Interdiction', 'crew': '2', 'cargo': '12'},
    {'name': 'Cutlass Red', 'manufacturer': 'Drake', 'role': 'Medical', 'crew': '2', 'cargo': '12'},
    {'name': 'Cutlass Steel', 'manufacturer': 'Drake', 'role': 'Dropship', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'Cutter', 'manufacturer': 'Drake', 'role': 'Light Freight', 'crew': '1', 'cargo': '4'},
    {'name': 'Cutter Rambler', 'manufacturer': 'Drake', 'role': 'Exploration', 'crew': '1', 'cargo': '2'},
    {'name': 'Cutter Scout', 'manufacturer': 'Drake', 'role': 'Exploration', 'crew': '1', 'cargo': '2'},
    {'name': 'Golem', 'manufacturer': 'Drake', 'role': 'Mining, Prospecting', 'crew': '1', 'cargo': '32'},
    {'name': 'Herald', 'manufacturer': 'Drake', 'role': 'Medium Data', 'crew': '1', 'cargo': '-'},
    {'name': 'Ironclad (In Production)', 'manufacturer': 'Drake', 'role': 'Heavy Freight', 'crew': '6', 'cargo': '1536'},
    {'name': 'Ironclad Assault (In Concept)', 'manufacturer': 'Drake', 'role': 'Heavy Dropship', 'crew': '6', 'cargo': '1152'},
    {'name': 'Kraken (In Production)', 'manufacturer': 'Drake', 'role': 'Light Carrier', 'crew': '10', 'cargo': '3792'},
    {'name': 'Kraken Privateer (In Concept)', 'manufacturer': 'Drake', 'role': 'Light Carrier, Trade', 'crew': '10', 'cargo': '768'},
    {'name': 'Vulture', 'manufacturer': 'Drake', 'role': 'Light Salvage', 'crew': '1', 'cargo': '12'},
    {'name': 'Blade', 'manufacturer': 'Esperia', 'role': 'Light Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Glaive', 'manufacturer': 'Esperia', 'role': 'Medium Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Prowler', 'manufacturer': 'Esperia', 'role': 'Dropship', 'crew': '2', 'cargo': '-'},
    {'name': 'Prowler Utility', 'manufacturer': 'Esperia', 'role': 'Medium Freight', 'crew': '2 - 5', 'cargo': '32'},
    {'name': 'Scythe', 'manufacturer': 'Esperia', 'role': 'Medium Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Talon', 'manufacturer': 'Esperia', 'role': 'Stealth', 'crew': '1', 'cargo': '-'},
    {'name': 'Talon Shrike', 'manufacturer': 'Esperia', 'role': 'Stealth, Bomber', 'crew': '1', 'cargo': '-'},
    {'name': 'Railen (In Production)', 'manufacturer': 'Gatac', 'role': 'Medium Freight', 'crew': '1 - 4', 'cargo': '320'},
    {'name': 'Syulen', 'manufacturer': 'Gatac', 'role': 'Light Freight', 'crew': '1', 'cargo': '6'},
    {'name': 'L-21 Wolf', 'manufacturer': 'Kruger', 'role': 'Light Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'P-52 Merlin', 'manufacturer': 'Kruger', 'role': 'Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'P-72 Archimedes', 'manufacturer': 'Kruger', 'role': 'Racing', 'crew': '1', 'cargo': '-'},
    {'name': 'P-72 Archimedes Emerald', 'manufacturer': 'Kruger', 'role': 'Racing', 'crew': '1', 'cargo': '-'},
    {'name': 'Endeavor (In Concept)', 'manufacturer': 'MISC', 'role': 'Heavy Science, Modular', 'crew': '3 - 5', 'cargo': '500'},
    {'name': 'Expanse (In Concept)', 'manufacturer': 'MISC', 'role': 'Refinery', 'crew': '1', 'cargo': '128'},
    {'name': 'Fortune', 'manufacturer': 'MISC', 'role': 'Light Salvage', 'crew': '1', 'cargo': '12'},
    {'name': 'Freelancer', 'manufacturer': 'MISC', 'role': 'Medium Freight', 'crew': '2 - 4', 'cargo': '66'},
    {'name': 'Freelancer DUR', 'manufacturer': 'MISC', 'role': 'Expedition', 'crew': '2 - 4', 'cargo': '36'},
    {'name': 'Freelancer Max', 'manufacturer': 'MISC', 'role': 'Medium Freight', 'crew': '2 - 4', 'cargo': '120'},
    {'name': 'Freelancer Mis', 'manufacturer': 'MISC', 'role': 'Gunship', 'crew': '2 - 4', 'cargo': '36'},
    {'name': 'Fury', 'manufacturer': 'MISC', 'role': 'Snub Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Fury LX', 'manufacturer': 'MISC', 'role': 'Snub Racing', 'crew': '1', 'cargo': '-'},
    {'name': 'Fury MX', 'manufacturer': 'MISC', 'role': 'Snub Bomber', 'crew': '1', 'cargo': '-'},
    {'name': 'Guardian', 'manufacturer': 'MISC', 'role': 'Heavy Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Guardian MX', 'manufacturer': 'MISC', 'role': 'Heavy Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Guardian QI', 'manufacturer': 'MISC', 'role': 'Heavy Fighter', 'crew': '1', 'cargo': '-'},
    {'name': 'Hull A', 'manufacturer': 'MISC', 'role': 'Medium Freight', 'crew': '1', 'cargo': '64'},
    {'name': 'Hull B (In Concept)', 'manufacturer': 'MISC', 'role': 'Heavy Freight', 'crew': '1', 'cargo': '384'},
    {'name': 'Hull C', 'manufacturer': 'MISC', 'role': 'Heavy Freight', 'crew': '2 - 4', 'cargo': '4608'},
    {'name': 'Hull D (In Concept)', 'manufacturer': 'MISC', 'role': 'Heavy Freight', 'crew': '3 - 5', 'cargo': '20736'},
    {'name': 'Hull E (In Concept)', 'manufacturer': 'MISC', 'role': 'Heavy Freight', 'crew': '4 - 5', 'cargo': '98304'},
    {'name': 'Odyssey (In Concept)', 'manufacturer': 'MISC', 'role': 'Exploration', 'crew': '4 - 6', 'cargo': '252'},
    {'name': 'Prospector', 'manufacturer': 'MISC', 'role': 'Mining, Prospecting', 'crew': '1', 'cargo': '-'},
    {'name': 'Razor', 'manufacturer': 'MISC', 'role': 'Racing', 'crew': '1', 'cargo': '-'},
    {'name': 'Razor EX', 'manufacturer': 'MISC', 'role': 'Stealth', 'crew': '1', 'cargo': '-'},
    {'name': 'Razor LX', 'manufacturer': 'MISC', 'role': 'Racing, Luxury', 'crew': '1', 'cargo': '-'},
    {'name': 'Reliant Kore', 'manufacturer': 'MISC', 'role': 'Light Freight', 'crew': '1 - 2', 'cargo': '6'},
    {'name': 'Reliant Mako', 'manufacturer': 'MISC', 'role': 'Reporting', 'crew': '2', 'cargo': '-'},
    {'name': 'Reliant Sen', 'manufacturer': 'MISC', 'role': 'Light Science', 'crew': '2', 'cargo': '-'},
    {'name': 'Reliant Tana', 'manufacturer': 'MISC', 'role': 'Light Fighter', 'crew': '1 - 2', 'cargo': '1'},
    {'name': 'Starfarer', 'manufacturer': 'MISC', 'role': 'Heavy Refuel', 'crew': '4 - 6', 'cargo': '291'},
    {'name': 'Starfarer Gemini', 'manufacturer': 'MISC', 'role': 'Heavy Refuel', 'crew': '4 - 6', 'cargo': '291'},
    {'name': 'Starlancer MAX', 'manufacturer': 'MISC', 'role': 'Medium Freight', 'crew': '1 - 4', 'cargo': '224'},
    {'name': 'Starlancer TAC', 'manufacturer': 'MISC', 'role': 'Patrol', 'crew': '1 - 6', 'cargo': '96'},
    {'name': '100i', 'manufacturer': 'Origin', 'role': 'Pathfinder', 'crew': '1', 'cargo': '2'},
    {'name': '125a', 'manufacturer': 'Origin', 'role': 'Light Fighter', 'crew': '1', 'cargo': '2'},
    {'name': '135c', 'manufacturer': 'Origin', 'role': 'Light Freight', 'crew': '1', 'cargo': '6'},
    {'name': '300i', 'manufacturer': 'Origin', 'role': 'Touring', 'crew': '1', 'cargo': '8'},
    {'name': '315p', 'manufacturer': 'Origin', 'role': 'Pathfinder', 'crew': '1', 'cargo': '12'},
    {'name': '325a', 'manufacturer': 'Origin', 'role': 'Light Fighter, Interdiction', 'crew': '1', 'cargo': '4'},
    {'name': '350r', 'manufacturer': 'Origin', 'role': 'Racing', 'crew': '1', 'cargo': '4'},
    {'name': '400i', 'manufacturer': 'Origin', 'role': 'Pathfinder', 'crew': '1 - 3', 'cargo': '42'},
    {'name': '600i Executive', 'manufacturer': 'Origin', 'role': 'Touring', 'crew': '3 - 5', 'cargo': '44'},
    {'name': '600i Explorer', 'manufacturer': 'Origin', 'role': 'Expedition', 'crew': '2 - 5', 'cargo': '44'},
    {'name': '600i Touring', 'manufacturer': 'Origin', 'role': 'Touring', 'crew': '3 - 5', 'cargo': '20'},
    {'name': '85x', 'manufacturer': 'Origin', 'role': 'Touring', 'crew': '1 - 2', 'cargo': '-'},
    {'name': '890 Jump', 'manufacturer': 'Origin', 'role': 'Touring', 'crew': '3 - 5', 'cargo': '388'},
    {'name': 'M50', 'manufacturer': 'Origin', 'role': 'Racing', 'crew': '1', 'cargo': '-'},
    {'name': 'Apollo Medivac', 'manufacturer': 'RSI', 'role': 'Medical', 'crew': '2', 'cargo': '32'},
    {'name': 'Apollo Triage', 'manufacturer': 'RSI', 'role': 'Medical', 'crew': '2', 'cargo': '32'},
    {'name': 'Arrastra (In Concept)', 'manufacturer': 'RSI', 'role': 'Heavy Mining', 'crew': '1 - 5', 'cargo': '576'},
    {'name': 'Aurora CL', 'manufacturer': 'RSI', 'role': 'Light Freight', 'crew': '1', 'cargo': '6'},
    {'name': 'Aurora ES', 'manufacturer': 'RSI', 'role': 'Pathfinder', 'crew': '1', 'cargo': '3'},
    {'name': 'Aurora LN', 'manufacturer': 'RSI', 'role': 'Light Fighter', 'crew': '1', 'cargo': '3'},
    {'name': 'Aurora LX', 'manufacturer': 'RSI', 'role': 'Pathfinder', 'crew': '1', 'cargo': '3'},
    {'name': 'Aurora MR', 'manufacturer': 'RSI', 'role': 'Light Fighter', 'crew': '1', 'cargo': '3'},
    {'name': 'Constellation Andromeda', 'manufacturer': 'RSI', 'role': 'Medium Freight, Gunship', 'crew': '3 - 4', 'cargo': '96'},
    {'name': 'Constellation Aquila', 'manufacturer': 'RSI', 'role': 'Expedition', 'crew': '3 - 4', 'cargo': '96'},
    {'name': 'Constellation Phoenix', 'manufacturer': 'RSI', 'role': 'Touring', 'crew': '3 - 4', 'cargo': '80'},
    {'name': 'Constellation Phoenix Emerald', 'manufacturer': 'RSI', 'role': 'Touring', 'crew': '3 - 4', 'cargo': '80'},
    {'name': 'Constellation Taurus', 'manufacturer': 'RSI', 'role': 'Medium Freight', 'crew': '3 - 4', 'cargo': '174'},
    {'name': 'Galaxy (In Concept)', 'manufacturer': 'RSI', 'role': 'Modular', 'crew': '1 - 6', 'cargo': '64'},
    {'name': 'Mantis', 'manufacturer': 'RSI', 'role': 'Interdiction', 'crew': '1', 'cargo': '-'},
    {'name': 'Orion (In Concept)', 'manufacturer': 'RSI', 'role': 'Heavy Mining', 'crew': '4 - 7', 'cargo': '384'},
    {'name': 'Perseus (In Production)', 'manufacturer': 'RSI', 'role': 'Heavy Gunship', 'crew': '6', 'cargo': '50'},
    {'name': 'Polaris', 'manufacturer': 'RSI', 'role': 'Corvette', 'crew': '6 - 14', 'cargo': '576'},
    {'name': 'Scorpius', 'manufacturer': 'RSI', 'role': 'Medium Fighter', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'Scorpius Antares', 'manufacturer': 'RSI', 'role': 'Medium Fighter, Interdiction', 'crew': '1 - 2', 'cargo': '-'},
    {'name': 'Zeus Mk II CL', 'manufacturer': 'RSI', 'role': 'Medium Freight', 'crew': '3', 'cargo': '128'},
    {'name': 'Zeus Mk II ES', 'manufacturer': 'RSI', 'role': 'Exploration', 'crew': '3', 'cargo': '32'},
    {'name': 'Zeus Mk II MR (In Concept)', 'manufacturer': 'RSI', 'role': 'Interdiction', 'crew': '3', 'cargo': '16'},
]